apiVersion: v1
data:
  password: MjQxMg==
  username: ZmFiaW90b3p6aQ==
kind: Secret
metadata:
  creationTimestamp: "2026-07-07T07:48:09Z"
  name: credentials
  namespace: default
  resourceVersion: "16652"
  uid: 195008d3-b5e3-4b7c-85a6-5b415d791c9c
type: Opaque
