apiVersion: v1
kind: Pod 
metadata: 
  name: podex # nome del pod
spec: # descrive cosa gira dentro il Pod
  containers: # lista di container che girano all'interno del pod
    - name: c-secret
      image: alpine
      command: ["sleep", "3600"] # comando eseguito all'interno del container, sleep per un'ora
      env: # lista delle variabili d'ambiente da aggiungere al container
        - name: sec_user
          valueFrom:
            secretKeyRef: # prende il valore de un secret 
              name: credentials
              key: username
        - name: sec_pass
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password