def IMAGE_TAG = ""

pipeline {
    agent any 

    
    stages {

        stage('Debug Git Vars') {
            steps {
                sh 'env | grep -i git'
                sh 'env | grep -i branch'
                sh 'env | grep -i tag'
            }
        }

        stage('Set Image Tag') {
            steps {
                script {
                    if (env.GIT_BRANCH == "origin/master") {
                        IMAGE_TAG = "latest"
                    }
                    else if (env.GIT_BRANCH == "origin/develop") {
                        IMAGE_TAG = "develop-" + env.GIT_COMMIT.take(7) 
                    }
                    else {
                        IMAGE_TAG = env.TAG_NAME
                    }
                }
            }
        }
        
        stage('Login DockerHub') {
            steps {
                
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials', 
                    usernameVariable: 'DOCKER_USER', 
                    passwordVariable: 'DOCKER_PASS' 
                )]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin' 
                }
            }
        }

        stage ('Date') {
            
            steps {

                script {
                    
                    //variabile dove prende il giorno di oggi
                    def GiornoSettimana = new Date().format('E')

                    //debug per verificare il valore della variabile
                    echo "Valore: ${GiornoSettimana}"

                    //se oggi è sabato o domenica interrompi e non fare la build, sennò vai avanti
                    if (GiornoSettimana == 'Sat' || GiornoSettimana == 'Sun') {
                        error "weekend niente build"
                    }
                    else {
                        sh 'echo "giorno lavorativo build eseguibile"'
                    }
                }
            }
        }
        
        stage('Build') {
           
            steps {
                echo "inizio Build [creazione immagine]"
                
                sh 'docker build -t flask-hello-world Step2/' 
            }
        }
    
        stage('Tag') {
            steps {
                echo "inizio tag imag"
                sh "docker tag flask-hello-world j3ynn/flask-hello-world:${IMAGE_TAG}" 
            }
        }

        stage('Push') {
            steps {
                echo "inizio push"
                sh "docker push j3ynn/flask-hello-world:${IMAGE_TAG}" 
            }
        }
    }
    
    
    post {
        always {
            sh 'docker logout'
        }
    }
}
