Vagrant.configure("2") do |config|

  config.vm.define "db" do |db|

  db.vm.box = "bento/ubuntu-22.04"
  db.vm.hostname = "db"
  db.vm.network "private_network", ip: "192.168.100.11"

  end

  config.vm.define "dbTow" do |db|

  db.vm.box = "bento/ubuntu-22.04"
  db.vm.hostname = "dbTow"
  db.vm.network "private_network", ip: "192.168.100.12"
  
  end

end
