# Il comando Vagrant.configure("2") è fondamentale perché dice a Vagrant 
# di usare le regole moderne (versione 2).
Vagrant.configure("2") do |config|

  # prima vm Ping
  config.vm.define "Ping" do |ping|

    # utilizziamo il comando per impostare un sistema operativo (ubuntu in questo caso)
    ping.vm.box = "ubuntu/focal64"

    # Port forwarding: inoltra il traffico dalla porta 8080 del mac alla porta 80 della VM
    ping.vm.network "forwarded_port", guest: 80, host: 8080

    ping.vm.provider "virtualbox" do |vb|
      # il valore è in Megabyte (1024 = 1 Gigabyte)
      vb.memory = "1024"
      # impostiamo una cpu
      vb.cpus = "1"
      # nome VM
      vb.name = "Ping"
      # utilizza il DNS del mac (ci traduce i nomi di dominio in IP)
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      # passa le richieste di rete attraverso il mac per collegarsi ad internet
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    # esegue lo script docker.sh dentro la VM per installare Docker.
    ping.vm.provision "shell", path: "Docker.sh"

  end

  # seconda vm Pong
  config.vm.define "Pong" do |pong|

    pong.vm.box = "ubuntu/focal64"

    # porta diversa da Ping per evitare conflitti
    pong.vm.network "forwarded_port", guest: 80, host: 8081

    pong.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "Pong"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    pong.vm.provision "shell", path: "Docker.sh"

  end

end